spring:
  application:
    name: eureka-server
server:
  port: 2002

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka3:2003/eureka