spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sylarjyd/sp-config
          searchPaths: config
          #username: your-username
          #password: your-password
    inetutils:
      ignored-interfaces: # 忽略的网卡
        - VM.*
      preferred-networks: # 要是用的网卡的网段
        - 192.168.10
  rabbitmq:
    host: 172.16.20.174
    port: 5672
    username: test
    password: test
server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka, http://eureka3:2003/eureka
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh